EXPERIMENT:
  NAME: ""
  TAG: "energykd,res56,res20"
  PROJECT: "cifar100_energy_based"
DISTILLER:
  TYPE: "energyKD"
  TEACHER: "resnet56"
  STUDENT: "resnet20"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 360
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210, 240, 270, 300]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
ENERGY:
  HIGH_RATE: 0.3
  LOW_RATE: 0.3
